-- MySQL Script generated by MySQL Workbench
-- 03/08/17 07:58:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cristoes_aseguradora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cristoes_aseguradora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cristoes_aseguradora` DEFAULT CHARACTER SET utf8 ;
USE `cristoes_aseguradora` ;

-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`aseguradora` (
  `rif` VARCHAR(45) NOT NULL,
  `cuentabancaria` VARCHAR(45) NULL DEFAULT NULL,
  `cedulacuentabancaria` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefonolocal` VARCHAR(45) NULL DEFAULT NULL,
  `telefonopersonal` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `fechafundacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rif`),
  UNIQUE INDEX `rif_UNIQUE` (`rif` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`corredor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`corredor` (
  `cedula` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `fecharegistro` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `aseguradora_rif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_corredor_aseguradora1_idx` (`aseguradora_rif` ASC),
  CONSTRAINT `fk_corredor_aseguradora1`
    FOREIGN KEY (`aseguradora_rif`)
    REFERENCES `cristoes_aseguradora`.`aseguradora` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`cita` (
  `cedula` INT(8) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `estatus` VARCHAR(20) NOT NULL DEFAULT 'En Espera',
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`asegurado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`asegurado` (
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `estado` INT(11) NULL DEFAULT '3',
  `corredor_cedula` VARCHAR(45) NOT NULL,
  `cedula` INT(8) NOT NULL,
  INDEX `fk_asegurado_corredor1_idx` (`corredor_cedula` ASC),
  INDEX `fk_asegurado_cita1_idx` (`cedula` ASC),
  PRIMARY KEY (`cedula`),
  CONSTRAINT `fk_asegurado_corredor1`
    FOREIGN KEY (`corredor_cedula`)
    REFERENCES `cristoes_aseguradora`.`corredor` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asegurado_cita1`
    FOREIGN KEY (`cedula`)
    REFERENCES `cristoes_aseguradora`.`cita` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`beneficiario` (
  `cedula` INT(10) UNSIGNED NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `asegurado_cedula` INT(8) NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_beneficiario_asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_beneficiario_asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `cristoes_aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`tipopolizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`tipopolizas` (
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `costo` VARCHAR(45) NULL DEFAULT NULL,
  `cobertura` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`tiposeguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`tiposeguro` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `observacion` VARCHAR(100) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`servicio` (
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `fechaadquisicion` DATE NULL DEFAULT NULL,
  `fechavigencia` DATE NULL DEFAULT NULL,
  `fechaculminacion` DATE NULL DEFAULT NULL,
  `beneficios` VARCHAR(45) NULL DEFAULT NULL,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `observaciones` VARCHAR(100) NULL DEFAULT NULL,
  `tipopolizas_codigo` VARCHAR(45) NOT NULL,
  `aseguradora_rif` VARCHAR(45) NOT NULL,
  `tiposeguro_codigo` VARCHAR(10) NOT NULL,
  `asegurado_cedula` INT(8) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_servicio_tipopolizas1_idx` (`tipopolizas_codigo` ASC),
  INDEX `fk_servicio_aseguradora1_idx` (`aseguradora_rif` ASC),
  INDEX `fk_servicio_tiposeguro1_idx` (`tiposeguro_codigo` ASC),
  INDEX `fk_servicio_asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_servicio_aseguradora1`
    FOREIGN KEY (`aseguradora_rif`)
    REFERENCES `cristoes_aseguradora`.`aseguradora` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tipopolizas1`
    FOREIGN KEY (`tipopolizas_codigo`)
    REFERENCES `cristoes_aseguradora`.`tipopolizas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tiposeguro1`
    FOREIGN KEY (`tiposeguro_codigo`)
    REFERENCES `cristoes_aseguradora`.`tiposeguro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `cristoes_aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`factura` (
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `montototal` VARCHAR(45) NULL DEFAULT NULL,
  `montocancelado` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Pendiente',
  `observaciones` VARCHAR(100) NULL DEFAULT NULL,
  `servicio_codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_factura_servicio1_idx` (`servicio_codigo` ASC),
  CONSTRAINT `fk_factura_servicio1`
    FOREIGN KEY (`servicio_codigo`)
    REFERENCES `cristoes_aseguradora`.`servicio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`gastos` (
  `codigo` VARCHAR(45) NOT NULL,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `reembolso` VARCHAR(45) NULL DEFAULT 'Pendiente',
  `estatus` VARCHAR(45) NULL DEFAULT 'Pendiente',
  `asegurado_cedula` INT(8) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_gastos_asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_gastos_asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `cristoes_aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`pagos_de_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`pagos_de_servicios` (
  `codigo` VARCHAR(45) NOT NULL,
  `servicio_codigo` VARCHAR(45) NOT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  INDEX `fk_pagos_de_servicios_factura1_idx` (`codigo` ASC),
  INDEX `fk_pagos_de_servicios_servicio1_idx` (`servicio_codigo` ASC),
  CONSTRAINT `fk_pagos_de_servicios_factura1`
    FOREIGN KEY (`codigo`)
    REFERENCES `cristoes_aseguradora`.`factura` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_de_servicios_servicio1`
    FOREIGN KEY (`servicio_codigo`)
    REFERENCES `cristoes_aseguradora`.`servicio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`polizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`polizas` (
  `tipopolizas_codigo` VARCHAR(45) NOT NULL,
  `corredor_cedula` VARCHAR(45) NOT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Activo',
  `asegurado_cedula` INT(8) NOT NULL,
  INDEX `fk_polizas_tipopolizas1_idx` (`tipopolizas_codigo` ASC),
  INDEX `fk_polizas_corredor1_idx` (`corredor_cedula` ASC),
  INDEX `fk_polizas_asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_polizas_corredor1`
    FOREIGN KEY (`corredor_cedula`)
    REFERENCES `cristoes_aseguradora`.`corredor` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polizas_tipopolizas1`
    FOREIGN KEY (`tipopolizas_codigo`)
    REFERENCES `cristoes_aseguradora`.`tipopolizas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polizas_asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `cristoes_aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`reembolsos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`reembolsos` (
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `gastos_codigo` VARCHAR(45) NOT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`gastos_codigo`),
  INDEX `fk_reembolsos_gastos1_idx` (`gastos_codigo` ASC),
  CONSTRAINT `fk_reembolsos_gastos1`
    FOREIGN KEY (`gastos_codigo`)
    REFERENCES `cristoes_aseguradora`.`gastos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cristoes_aseguradora`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cristoes_aseguradora`.`usuarios` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(28) NOT NULL,
  `nivel` INT(1) NOT NULL,
  `cookie` INT(10) NOT NULL,
  `logueado` VARCHAR(2) NOT NULL,
  `cedula` INT(8) NOT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'Inactivo',
  PRIMARY KEY (`ID`),
  INDEX `fk_usuarios_cita1_idx` (`cedula` ASC),
  CONSTRAINT `fk_usuarios_cita1`
    FOREIGN KEY (`cedula`)
    REFERENCES `cristoes_aseguradora`.`cita` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
